name: syzygy
description: Game Test
version: 0.0.0
publish_to: none

environment:
  sdk: ^2.17.0
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.7.0

flutter:
  assets:
    - assets/images/